### PR TITLE
Few fixes and new features

### PR DESCRIPTION
**Pull request by demarchisd**
- EXIF Orientation fix
- Removed the input file from the directive and added a src attribute, so it's possible to load the source image in any way
- Removed the "Crop" button from the directive and added a crop attribute, so it's possible to trigger the crop event in any way
- Added a result-blob attribute that will contain the cropped image in a Blob object
- Added a padding attribute, so it's possible to change the canvas' total size
- Added a maxSize attribute. If set, the source image will be reduced according to the informed size (pixels)
- Change in the way that the crop handles the limits of the image - now it's softer
- Added the capability of zooming with the mouse's wheel
- Sometimes the crop shape was loading out of the image's limits. Fixed to move the shape to the image's center when loaded.

### CODE REVIEW

**Comment by andyshora** [comment]
Wow, thank you @demarchisd! I'll test it out this week!

**Comment by demarchisd** [comment]
Great! Feel free to adjust the code the way you like.. if there's something that I can help, please let me know!

**Comment by galuszkak** [comment]
Looks awesome @demarchisd . Will you merge that @andyshora  and release new version on bower? Thanks for great directive :) .

**Comment by rhutchison** [comment]
+1

**Comment by andyshora** [comment]
Done, and should be available on bower as v2.0.0.

Thanks again, @demarchisd. Sorry this one slipped massively off my radar! So happy you guys are using it :-)

**Pull request merged**
